name: Portfolio CI/CD

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  # =========================
  # QUALITY
  # =========================

  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Vérifier le code
        run: npm run lint

      - name: Lancer les tests
        run: npm test

      - name: Vérifier le build
        run: npm run build


  # =========================
  # SECURITY
  # =========================

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Audit des dépendances
        run: npm audit --audit-level=high


  # =========================
  # DOCKER
  # =========================

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    needs:
      - quality
      - security

    permissions:
      contents: read
      packages: write

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Se connecter à GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construire l'image Docker
        run: |
          docker build \
            -t ghcr.io/pelagie-aintangar/portfolio:latest \
            -t ghcr.io/pelagie-aintangar/portfolio:${{ github.sha }} \
            .

      - name: Publier l'image sur GHCR
        run: |
          docker push ghcr.io/pelagie-aintangar/portfolio:latest
          docker push ghcr.io/pelagie-aintangar/portfolio:${{ github.sha }}

  # =========================
  # KUBERNETES
  # =========================
    