name: Portfolio CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main


jobs:

  # =========================
  # QUALITY
  # =========================

  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Vérifier le code
        run: npm run lint

      - name: Lancer les tests
        run: npm test

      - name: Vérifier le build
        run: npm run build


  # =========================
  # SECURITY
  # =========================

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Audit des dépendances
        run: npm audit --audit-level=high


  # =========================
  # DOCKER
  # =========================

  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    needs:
      - quality
      - security

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t pelagie-portfolio .